# frozen_string_literal: true
# AUTO-GENERATED BY openapi_codegen - DO NOT EDIT MANUALLY
# GENERATED-FROM: #/components/schemas/HealthOkResponse
# GENERATED-HASH: b414d971b9295c800c770b4bb821a45fd783a8fa
# This serializer was generated from OpenAPI response schema
class HealthSerializer
  include JSONAPI::Serializer

  attributes :message, :test


# BEGIN AUTO-GENERATED EXAMPLES
EXAMPLES = {

  "index" => { "message" => "I'm up!", "test" => 123 },

}
# END AUTO-GENERATED EXAMPLES
  # Per-action response helpers generated from OpenAPI
  
  def self.index_response(data = nil)
    example = EXAMPLES["index"]
    new(data || example || {}).serializable_hash
  end
  

end
