# frozen_string_literal: true

# AUTO-GENERATED BY openapi_routes_generator - DO NOT EDIT MANUALLY
class HealthController < ApplicationController

  # default action template
  # available vars: action (String), controller (String), path (String), method (String)
  def index
    # TODO: implement index for health#index
    # path: /up, method: GET
    render json: {}, status: :ok
  end
end
