# frozen_string_literal: true
# AUTO-GENERATED BY openapi_routes_generator - DO NOT EDIT MANUALLY
class HealthController < ApplicationController

  # default action template
  # available vars: action (String), controller (String), path (String), method (String), serializer_class (String), example (String - Ruby literal)
  def index

  # This action calls the corresponding serializer (data supplied by serializer examples when nil).
  render json: HealthSerializer.index_response, status: :ok

  end
end
