openapi: 3.0.3
info:
  title: Enman API
  version: 0.1.1
servers:
  - description: Local development server
    url: http://localhost:3000
tags:
  - name: health
    description: Endpoints related to health checks and status monitoring
paths:
  /welcome:
    $ref: ./paths/welcome.yaml